### ISSUE TITLE
error at launch - unable to open database file

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [imagodata/filter_mate#2]
Hi,

at launch of the plugin, QGIS throws this error.
Can I do something to test what is going on?
This is on a Windows10 machine with QGIS 3.34.5

Traceback (most recent call last):
  File "C:\Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\filter_mate\filter_mate.py", line 296, in run
    self.app = FilterMateApp(self.plugin_dir)
  File "C:\Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\filter_mate\filter_mate_app.py", line 82, in __init__
    self.run()
  File "C:\Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\filter_mate\filter_mate_app.py", line 99, in run
    self.init_filterMate_db()
  File "C:\Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\filter_mate\filter_mate_app.py", line 605, in init_filterMate_db
    conn = spatialite_connect(self.db_file_path)
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 756, in spatialite_connect
    con = sqlite3.dbapi2.connect(*args, **kwargs)
sqlite3.OperationalError: unable to open database file

Python versie: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS versie: 3.34.5-Prizren Prizren, 4b308492

**Comment by Jeroen-GroeneBij** [comment]
Update on this issue:
Without doing any updates or making changes to QGIS or the plugin, I am now able to 'open' the plugin and see the Filter_mate panel. However, the python error still appears.
I can't seem to do anything in the panel, I can only open and close the different sections.

In the section Configuration I do find a weird entry:
In App > Options > the APP_SQLITE_PATH is set to a c:\Users\simon folder which most certainly does not exist on my machine :), see also attached picture:
![afbeelding](https://github.com/sducournau/filter_mate/assets/26653761/c65c4de8-1234-4071-8608-12c658cc279d)

**Comment by imagodata** [comment]
Re-audit 2026-04-27 : résolu. Le chemin SQLite est désormais dérivé dynamiquement de `QgsApplication.qgisSettingsDirPath()` via `PLUGIN_CONFIG_DIRECTORY` (config/config.py:245), avec création automatique du répertoire (config/config.py:248-261) et fallback en mémoire si I/O échoue (config/config.py:363). Fix livré commits fa9627d7 + 0a47ce23. Fermeture — réouvrir si reproduit sur QGIS ≥ 3.34.
